language: python

python:
    - 2.7
    - 3.5
    - 3.6

install:
    - sudo apt-get update
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b
    - export PATH="$HOME/miniconda3/bin:$PATH"
    - conda update -n base conda
    - conda create -n test-env python=$TRAVIS_PYTHON_VERSION pytest
    - conda activate test-env
    - pip install -e .

script: py.test -s

